#
# CI Management
#
# This workflow manages the continuous integration infrastructure. It does not
# execute the CI, but instead builds the required containers, prepares the
# infrastructure, and imports required services.
#
name: "CI Management"

# We only re-run whenever you modify the sources of the CI, or if you tag a new
# version of the CI. This avoids burning CI resources needlessly for every push
# to the repository.
on:
  pull_request:
    branches:
    - "ci/*"
  push:
    branches:
    - "ci/*"
    tags:
    - "ci-*"

jobs:
  #
  # Create Containers
  #
  # This job builds and optionally pushes containers from `.github/containers/`
  # to github-packages. Depending on the source ref, a different operation is
  # performed:
  #
  #   * `refs/tags/ci/rcX`: If a tag like `ci/rc12` is pushed, all containers
  #     are built and pushed to github-packages with that tag-name.
  #
  #   * In all other cases, the containers are built but immediately discarded.
  #
  create_containers:
    name: "Create Containers"
    runs-on: ubuntu-latest
    steps:
    - name: "Clone Repository"
      uses: actions/checkout@v2
    - name: "Authenticate to GitHub Packages"
      if: ${{ startsWith(github.ref, 'refs/tags/ci-rc') }}
      run: |
        echo "${{ github.token }}" \
        | docker login \
            docker.pkg.github.com \
            --password-stdin \
            -u "${{ github.actor }}"
    - name: "Build and Push Containers"
      run: |
        make \
          "CI_PUSH=${{ startsWith(github.ref, 'refs/tags/ci-rc') }}" \
          "CI_REF=${{ github.ref }}" \
          "CI_REGISTRY=docker.pkg.github.com" \
          "CI_REPOSITORY=${{ github.repository }}" \
          ci-create
