name: Tests

on: [pull_request, push]

jobs:
  test_suite:
    name: "Test Suite"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        test:
        - "test.mod"
        - "test.run.test_assemblers"
        - "test.run.test_boot"
        - "test.run.test_noop"
        - "test.run.test_sources"
        - "test.run.test_stages"
        - "test.src"

    services:
      fedmir:
        image: "docker.io/osbuilders/ghci-osbuild-fedmir:v1"
        ports: ["8071:80"]

    steps:
    - name: "Clone Repository"
      uses: actions/checkout@v2
    - name: "Wait for FedMir"
      uses: osbuild/containers/src/actions/netwait@v1
      with:
        port: "8071"
    - name: "Run Tests"
      uses: osbuild/containers/src/actions/ghci-osbuild@v1
      with:
        run: |
          python3 -m unittest discover \
            -k "${{ matrix.test }}" \
            -s "test" \
            -t . \
            -v

  documentation:
    name: "📚 Documentation"
    runs-on: ubuntu-latest
    container:
      image: docker.io/library/python:3.7
    steps:
      - name: Install Dependencies
        run: |
          pip install docutils

      - name: Clone repository
        uses: actions/checkout@v2
        with:
          path: osbuild

      - name: Generate Documentation
        run: |
          make \
            -f osbuild/Makefile \
            SRCDIR=osbuild \
            BUILDDIR=build \
            RST2MAN=rst2man.py \
            man

      - name: Verify Documentation
        working-directory: build
        run: |
          test -d docs
          test -f docs/osbuild.1

  sample_validation:
    name: "sample validation"
    runs-on: ubuntu-latest
    container:
      image: docker.io/library/python:3.7
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          path: osbuild

      - name: Install Dependencies
        run: |
          pip install jsonschema

      - name: Validate the samples
        run: |
          cd osbuild
          for f in samples/*; do
            python3 -m osbuild --libdir . --inspect "$f" > /dev/null
          done

  test_data:
    name: "Regenerate Test Data"
    runs-on: ubuntu-latest
    steps:
    - name: "Clone Repository"
      uses: actions/checkout@v2
    - name: "Regenerate Test Data"
      uses: osbuild/containers/ghci/actions/ghci-osbuild@ghci/v1
      with:
        run: |
          make test-data
          git diff --exit-code -- ./test/data
